---
########################
########################
## SAST GitHub Action ##
########################
########################
name: SAST

#######################################
# Start the job on all push to master #
#######################################
on:
  push:
  pull_request:
    branches: ['master']

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: SAST

    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      #####################
      # Run Deploy script #
      #####################
      - name: Run SAST check
        uses: IvanKuchin/SAST@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
        env:
          LOG_VERBOSE: true
